import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { MainProvider } from "../components/MainProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Click Head",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </MainProvider>
      </body>
    </html>
  );
}
